### ISSUE TITLE
Additional fields required for ProjectList api.

### ISSUE THREAD

**Issue by adammacleod** [sprucedev/DockCI#334]
The following fields need to be added into the ProjectList API as per the current front end designs:

- repo
- Build status slug (eg: DCM891V) (I'm not sure what this is?)

![screen shot 2015-11-09 at 9 19 52 am](https://cloud.githubusercontent.com/assets/397073/11023089/0dd8c528-86c3-11e5-80fc-12b4bd63a092.png)

- Status of the last Job
- Elapsed time since queued, broken or failed jobs.
- Avatar for the build, not sure where this would actually come from?

For the following I'm not sure if it would be better to sort/calculate on the UI or pass along in the payload: (if we ever paginate at the server it will obviously need to be a server concern)
- Sum of queued/passing/failing/broken jobs
- Total number of jobs
- Most recent jobs

Lastly: 
- Ability to request only utilities or projects, if we intend to keep a seperate page for utilities/projects.

**Comment by RickyCook** [comment]
the DCM891V is the project ID. before the DB ovehaul, it was a 5 letter datetime-influenced thing that was sortable. the idea is that it needed to be sorted chronologically, but shouldn't be a sequence (because build 1 on master, build 2 on dev-branch is meaningless)

re last job, i _think_ that's how it's working now. i've had a thought for a while that project status should be the status of master, rather than last built. agree? i'll output whatever it is now, but food for thought i guess

do you mean elapsed time since any action, or elapsed time since specifically those statuses? (because that's kind of a "time since last failure", which ignores success; could be useful)

the avatar for the build is the git author id, which is currently just gravatar but in the future probably pulled from git{hub,lab} if available

what would the definition of "most recent" jobs be?

i think you can already request one or the other, but i could be totally wrong. if not, yeah definitely (but i also think it'd be benificial to preload the alternate type so that it's faster)

**Comment by RickyCook** [comment]
we should put up the UI mock ups somewhere with auth so that we can quickly load them up.. i cant remember where/how to look at it tbh

**Comment by RickyCook** [comment]
yeah so you can hit `/api/v1/projects?utility=yes` `/api/v1/projects?utility=no`

**Comment by adammacleod** [comment]
> the DCM891V is the project ID. before the DB ovehaul, it was a 5 letter datetime-influenced thing that was sortable. the idea is that it needed to be sorted chronologically, but shouldn't be a sequence (because build 1 on master, build 2 on dev-branch is meaningless)

Ah, in that case can we include the last commit ID and last tag (if that last job was a tag?). That way we can show a link to the specific job as well as the list of jobs.

> re last job, i think that's how it's working now. i've had a thought for a while that project status should be the status of master, rather than last built. agree? i'll output whatever it is now, but food for thought i guess

I'm actually not sure, maybe it needs to be configurable. I only say because at work we work on the dev branch, and for CI purposes that's the one we care about!

> do you mean elapsed time since any action, or elapsed time since specifically those statuses? (because that's kind of a "time since last failure", which ignores success; could be useful)

Elapsed time since the last job only.

> the avatar for the build is the git author id, which is currently just gravatar but in the future probably pulled from git{hub,lab} if available

Is it possible to return the fully formed avatar link? That way it becomes a backend concern and I don't need to concat/perform anything.

> what would the definition of "most recent" jobs be?

Chrono sorted from most recent to least recent. IE: 5 projects, time of last job run on each one sorted newest to oldest.

> i think you can already request one or the other, but i could be totally wrong. if not, yeah definitely (but i also think it'd be benificial to preload the alternate type so that it's faster)

Saw your update on this, will update code :)

> we should put up the UI mock ups somewhere with auth so that we can quickly load them up.. i cant remember where/how to look at it tbh

The front end is slowly going to diverge, we should get a hosted instance to play with :)

**Comment by RickyCook** [comment]
add to `/api/v1/projects`

[] clone uri
[] recent filter

**meta**
[] queued count
[] passing count
[] failing count
[] broken count
[] total jobs

**last completed**
[] id
[] status
[] time
[] avatar uri

**Comment by RickyCook** [comment]
Clone URI in #352

**Comment by RickyCook** [comment]
Added pass, fail, broken, total counts in #354. I won't do queued just yet, because it's actually a little difficult and not really meaningful at the moment. Up for discussion about that last one too.

**Comment by RickyCook** [comment]
Should note:

- meta details is `/api/v1/projects?meta=true`
- latest job details is `/api/v1/projects?latest_job=true`

These can be used together

Adding `latest_job=true` will give you:

```json
{
  "items": [
    {
      "latest_job": {
        "detail": "/api/v1/dockci/jobs/000000",
        "status": "success",
        "create_ts": "2015-12-12T12:12:12.000012"
      },
      "display_repo": "https://oauth2:****@github.com/sprucedev/DockCI.git"
    }
  ]
}
```

**Comment by RickyCook** [comment]
Completing for now, may return depending on how the other UI elements progress
